# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 21:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student_n', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('expert_n', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('student_cmd_n', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)])),
                ('expert_cmd_n', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vacs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacs.Experiment')),
            ],
        ),
    ]
