# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 01:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacs', '0002_auto_20170703_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentLexicon', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('Done', models.BooleanField(default=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacs.Command')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacs.Experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replication1', jsonfield.fields.JSONField()),
                ('replication2', jsonfield.fields.JSONField()),
                ('replication3', jsonfield.fields.JSONField()),
            ],
        ),
    ]
