# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacs', '0004_auto_20170703_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='currentLexicon',
            new_name='current_lexicon',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='experiment',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Done',
            field=models.BooleanField(default=False),
        ),
    ]
