# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacs', '0005_auto_20170705_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Done',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='replication1',
            new_name='replications',
        ),
    ]
