# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 01:11
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacs', '0008_auto_20170710_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='replications',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
