# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacs', '0013_auto_20170713_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='experiment',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lexicon_order',
            field=models.CharField(max_length=200),
        ),
    ]
