# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 16:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacs', '0014_auto_20170713_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='user',
        ),
        migrations.AddField(
            model_name='assignment',
            name='current_vac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_assigned', to='vacs.Vac'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='evaluated_vacs',
            field=models.ManyToManyField(blank=True, related_name='evaluated_assigned', to='vacs.Vac'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vacs.Assignment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='current_comparison',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
