# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 01:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vacs', '0017_evaluation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 15, 1, 28, 36, 353570, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
