# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 05:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacs', '0019_experiment_in_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='lexicon_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
            preserve_default=False,
        ),
    ]
