# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 01:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacs', '0020_score_lexicon_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexicon_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('done', models.BooleanField(default=False)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacs.Command')),
                ('current_vac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_val_assigned', to='vacs.Vac')),
                ('evaluated_vacs', models.ManyToManyField(blank=True, related_name='evaluated_val_assigned', to='vacs.Vac')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='val_replications',
            field=models.TextField(blank=True),
        ),
    ]
