# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacs', '0021_auto_20170731_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vacs.Score')),
                ('selected_lexicons', models.CharField(default='empty', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='valassignment',
            name='current_vac',
        ),
        migrations.RemoveField(
            model_name='valassignment',
            name='evaluated_vacs',
        ),
        migrations.AddField(
            model_name='valassignment',
            name='current_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_val_assigned', to='vacs.Score'),
        ),
        migrations.AddField(
            model_name='valassignment',
            name='evaluated_scores',
            field=models.ManyToManyField(blank=True, related_name='evaluated_val_assigned', to='vacs.Score'),
        ),
    ]
