# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacs', '0022_auto_20170801_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='valassignment',
            name='previous_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_val_assigned', to='vacs.Validation'),
        ),
    ]
