# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacs', '0023_valassignment_previous_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='valassignment',
            name='current_color',
            field=models.IntegerField(default=0),
        ),
    ]
